---

# Ensure SAP AnyDB, SAP HANA or SAP NetWeaver hostname is not localhost in /etc/hosts. See SAP Note 1054467 - Local host name refers to loopback address

- name: Ansible Play for controlling execution to an Infrastructure Platform when High Availability is used
  when:
    - (groups["hana_secondary"] is defined and (groups["hana_secondary"] | length>0)) or (groups["nwas_ers"] is defined and (groups["nwas_ers"] | length>0)) or (groups["anydb_secondary"] is defined and (groups["anydb_secondary"] | length>0))
  block:

    # Required to collect the remote host's facts for further processing
    # in the following steps and activate Ansible Special Variables
    # such as ansible_domain and ansible_fqdn
    - name: Gather host facts
      ansible.builtin.setup:


    - name: Update /etc/hosts file for SAP HANA Secondary node
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line: "{{ sap_vm_provision_dynamic_inventory_hana_secondary_ip }}\t{{ sap_vm_provision_dynamic_inventory_hana_secondary_hostname }}.{{ ansible_domain }}\t{{ sap_vm_provision_dynamic_inventory_hana_secondary_hostname }}"
        state: present
      when:
        - (groups["hana_secondary"] is defined and (groups["hana_secondary"] | length>0))

    - name: Update /etc/hosts file for SAP NetWeaver ERS
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line: "{{ sap_vm_provision_dynamic_inventory_nw_ers_ip }}\t{{ sap_vm_provision_dynamic_inventory_nw_ers_hostname }}.{{ ansible_domain }}\t{{ sap_vm_provision_dynamic_inventory_nw_ers_hostname }}"
        state: present
      when:
        - (groups["nwas_ers"] is defined and (groups["nwas_ers"] | length>0))


    - name: Update /etc/hosts file for SAP HANA HA
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "{{ sap_vm_provision_dynamic_inventory_hana_primary_ip }}\t{{ sap_vm_provision_dynamic_inventory_hana_primary_hostname }}.{{ ansible_domain }}\t{{ sap_vm_provision_dynamic_inventory_hana_primary_hostname }}"
        - "{{ sap_vm_provision_dynamic_inventory_hana_secondary_ip }}\t{{ sap_vm_provision_dynamic_inventory_hana_secondary_hostname }}.{{ ansible_domain }}\t{{ sap_vm_provision_dynamic_inventory_hana_secondary_hostname }}"
      when:
        - (groups["hana_secondary"] is defined and (groups["hana_secondary"] | length>0))

    - name: Update /etc/hosts file with Virtual IPs for SAP HANA HA
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "{{ (sap_ha_pacemaker_cluster_vip_hana_primary_ip_address | default('192.168.1.90/32')) | regex_replace('/.*', '') }}\t{{ sap_swpm_db_host }}.{{ ansible_domain }}\t{{ sap_swpm_db_host }}"
      when:
        - (groups["hana_secondary"] is defined and (groups["hana_secondary"] | length>0))
        - (not ansible_product_name == "Google Compute Engine" and not ansible_chassis_vendor == "Microsoft Corporation" and not ansible_chassis_asset_tag == 'ibmcloud') or ( (ansible_product_name == "Google Compute Engine" or ansible_chassis_vendor == "Microsoft Corporation" or ansible_chassis_asset_tag == 'ibmcloud') and (not inventory_hostname in groups["hana_primary"] or not inventory_hostname in groups["hana_secondary"]) )


    - name: Update /etc/hosts file for SAP AnyDB HA
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "{{ sap_vm_provision_dynamic_inventory_anydb_primary_ip }}\t{{ sap_vm_provision_dynamic_inventory_anydb_primary_hostname }}.{{ ansible_domain }}\t{{ sap_vm_provision_dynamic_inventory_anydb_primary_hostname }}"
        - "{{ sap_vm_provision_dynamic_inventory_anydb_secondary_ip }}\t{{ sap_vm_provision_dynamic_inventory_anydb_secondary_hostname }}.{{ ansible_domain }}\t{{ sap_vm_provision_dynamic_inventory_anydb_secondary_hostname }}"
      when:
        - (groups["anydb_secondary"] is defined and (groups["anydb_secondary"] | length>0))

    - name: Update /etc/hosts file with Virtual IPs for SAP AnyDB HA
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "{{ (sap_vm_temp_vip_anydb_primary | default('192.168.1.90/32')) | regex_replace('/.*', '') }}\t{{ sap_swpm_db_host }}.{{ ansible_domain }}\t{{ sap_swpm_db_host }}"
      when:
        - (groups["anydb_secondary"] is defined and (groups["anydb_secondary"] | length>0))


    - name: Update /etc/hosts file for SAP NetWeaver HA
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "{{ sap_vm_provision_dynamic_inventory_nw_ascs_ip }}\t{{ sap_vm_provision_dynamic_inventory_nw_ascs_hostname }}.{{ ansible_domain }}\t{{ sap_vm_provision_dynamic_inventory_nw_ascs_hostname }}"
        - "{{ sap_vm_provision_dynamic_inventory_nw_ers_ip }}\t{{ sap_vm_provision_dynamic_inventory_nw_ers_hostname }}.{{ ansible_domain }}\t{{ sap_vm_provision_dynamic_inventory_nw_ers_hostname }}"
        - "{{ sap_vm_provision_dynamic_inventory_nw_pas_ip }}\t{{ sap_vm_provision_dynamic_inventory_nw_pas_hostname }}.{{ ansible_domain }}\t{{ sap_vm_provision_dynamic_inventory_nw_pas_hostname }}"
      when:
        - (groups["nwas_ers"] is defined and (groups["nwas_ers"] | length>0))

    - name: Update /etc/hosts file with Virtual IPs for SAP NetWeaver HA - ASCS / ERS
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "{{ (sap_ha_pacemaker_cluster_vip_nwas_abap_ascs_ip_address | default('192.168.2.10/32')) | regex_replace('/.*', '') }}\t{{ sap_swpm_ascs_instance_hostname }}.{{ ansible_domain }}\t{{ sap_swpm_ascs_instance_hostname }}"
        - "{{ (sap_ha_pacemaker_cluster_vip_nwas_abap_ers_ip_address | default('192.168.2.11/32')) | regex_replace('/.*', '') }}\t{{ sap_swpm_ers_instance_hostname }}.{{ ansible_domain }}\t{{ sap_swpm_ers_instance_hostname }}"
      when:
        - (groups["nwas_ers"] is defined and (groups["nwas_ers"] | length>0))
        - not ansible_chassis_asset_tag == 'ibmcloud' or ((not inventory_hostname_short in groups['nwas_ascs'] and not inventory_hostname_short in groups['nwas_ers']) and ansible_chassis_asset_tag == 'ibmcloud')

    # - name: Update /etc/hosts file with Virtual IPs for SAP NetWeaver HA - PAS / AAS
    #   ansible.builtin.lineinfile:
    #     dest: /etc/hosts
    #     line: "{{ item }}"
    #     state: present
    #   loop:
    #     - "{{ (sap_ha_pacemaker_cluster_vip_nwas_abap_pas_ip_address | default('192.168.2.12/32')) | regex_replace('/.*', '') }}\t{{ sap_swpm_pas_instance_hostname }}.{{ ansible_domain }}\t{{ sap_swpm_pas_instance_hostname }}"
    #     - "{{ (sap_ha_pacemaker_cluster_vip_nwas_abap_aas_ip_address | default('192.168.2.13/32')) | regex_replace('/.*', '') }}\t{{ .sap_swpm_aas_instance_hostname }}.{{ ansible_domain }}\t{{ sap_swpm_aas_instance_hostname }}"
    #   when:
    #     - (groups["nwas_aas"] is defined and (groups["nwas_aas"] | length>0))
    #     - not ansible_chassis_asset_tag == 'ibmcloud' or ((not inventory_hostname_short in groups['nwas_pas'] and not inventory_hostname_short in groups['nwas_pas']) and ansible_chassis_asset_tag == 'ibmcloud')

    - name: Update /etc/hosts file for SAP NetWeaver AAS
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "{{ sap_vm_provision_dynamic_inventory_nw_aas_ip }}\t{{ sap_vm_provision_dynamic_inventory_nw_aas_hostname }}.{{ ansible_domain }}\t{{ sap_vm_provision_dynamic_inventory_nw_aas_hostname }}"
      when:
        - (groups["nwas_aas"] is defined and (groups["nwas_aas"] | length>0))


# Ensure SAP AnyDB, SAP HANA or SAP NetWeaver hostname is not localhost in /etc/hosts. See SAP Note 1054467 - Local host name refers to loopback address.
# However, as IBM Cloud Load Balancer is a secure design using Back-end Pool servers with singular Port Number and Front-end Listener with single Port Number,
# and controls the Virtual IP from the Load Balancer. Therefore the Virtual IP is not added as a Secondary IP to the OS Network Interface,
# which causes connectivity issues due to SAP NetWeaver instance random dynamic port usage.
# As workaround, configure /etc/hosts to map Virtual Hostname to use the host IP Address instead of the Virtual IP Address
- name: Ansible Play for controlling execution to an Infrastructure Platform when High Availability is used - IBM Cloud
  when:
    - (groups["hana_secondary"] is defined and (groups["hana_secondary"] | length>0)) or (groups["nwas_ers"] is defined and (groups["nwas_ers"] | length>0)) or (groups["anydb_secondary"] is defined and (groups["anydb_secondary"] | length>0))
    - ansible_chassis_asset_tag == 'ibmcloud'
  block:

    - name: Update /etc/hosts file with Virtual Hostname for SAP NetWeaver HA ASCS on IBM Cloud
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "{{ sap_vm_provision_dynamic_inventory_nw_ascs_ip }}\t{{ sap_swpm_ascs_instance_hostname }}.{{ ansible_domain }}\t{{ sap_swpm_ascs_instance_hostname }}"
        - "{{ (sap_ha_pacemaker_cluster_vip_nwas_abap_ers_ip_address | default('192.168.2.11/32')) | regex_replace('/.*', '') }}\t{{ sap_swpm_ers_instance_hostname }}.{{ ansible_domain }}\t{{ sap_swpm_ers_instance_hostname }}"
      when:
        - (groups["nwas_ers"] is defined and (groups["nwas_ers"] | length>0))
        - ansible_chassis_asset_tag == 'ibmcloud'
        - inventory_hostname_short in groups['nwas_ascs']

    - name: Update /etc/hosts file with Virtual Hostname for SAP NetWeaver HA ERS on IBM Cloud
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "{{ (sap_ha_pacemaker_cluster_vip_nwas_abap_ascs_ip_address | default('192.168.2.10/32')) | regex_replace('/.*', '') }}\t{{ sap_swpm_ascs_instance_hostname }}.{{ ansible_domain }}\t{{ sap_swpm_ascs_instance_hostname }}"
        - "{{ sap_vm_provision_dynamic_inventory_nw_ers_ip }}\t{{ sap_swpm_ers_instance_hostname }}.{{ ansible_domain }}\t{{ sap_swpm_ers_instance_hostname }}"
      when:
        - (groups["nwas_ers"] is defined and (groups["nwas_ers"] | length>0))
        - ansible_chassis_asset_tag == 'ibmcloud'
        - inventory_hostname_short in groups['nwas_ers']
