---

# When SAP HANA Scale-Out is used, if host name is not in original specifications then strip suffix node number from host name
- name: Set fact for storage setup when performing SAP HANA Scale-Out
  ansible.builtin.set_fact:
    host_node_scaleout_origin_spec: "{{ ansible_hostname | regex_replace('^(.+?)\\d*$', '\\1') }}"
  when:
    - sap_vm_provision_calculate_sap_hana_scaleout_active_coordinator is defined
    - not inventory_hostname in vars[ansible_prompt_iac_platform_choice + '_host_specifications_dictionary'][sap_vm_provision_host_specification_plan].keys()

# Use inventory_hostname_short to retrieve host specification from the dictionary. While ansible_hostname will work for Ansible only, using Ansible>Terraform may see ansible_hostname as 'localhost' and fail
# For end user ease of use, the host specifications dictionary uses disk_count to indicate how many disks will be provisioned
# However the sap_storage_setup Ansible Role can not detect disk_count, and requires the key to be renamed lvm_lv_stripes
- name: Convert sap_vm_provision_*_host_specifications_dictionary.storage_definition to sap_storage_setup.sap_storage_setup_definition
  ansible.builtin.set_fact:
    sap_storage_setup_definition: "{{ sap_storage_setup_definition | default([]) + [converted_element] }}"
  vars:
    converted_element: |
      {% set current_element = (convert_item | dict2items) %}
      {% set new_element = [] %}
      {% for entry in current_element %}
        {%- if "disk_count" in entry.key %}
          {%- set conv = new_element.extend([
            {
              'key': 'lvm_lv_stripes',
              'value': entry.value,
            }
          ]) %}
        {%- elif not "disk_type" in entry.key %}
          {%- set add_entry = new_element.extend([
            {
              'key': entry.key,
              'value': entry.value,
            }
          ]) %}
        {%- endif -%}
      {% endfor %}
      {{ new_element | items2dict }}
  loop: "{{ host_specifications_dictionary[sap_vm_provision_host_specification_plan][host_node_scaleout_origin_spec | default(inventory_hostname_short)].storage_definition | list }}"
  loop_control:
    loop_var: convert_item
    label: "{{ convert_item.name }}"
