---
# The tasks in this file are executed in a loop over the defined hosts

- name: Ensure short hostname is not longer than 13 characters (see SAP Note 611361)
  ansible.builtin.assert:
    that: (inventory_hostname | length | int) <= (13 | int)
    fail_msg: "FAIL: The length of the hostname is {{ inventory_hostname | length | int }} but must be less or equal to 13 characters!"

# When SAP HANA Scale-Out is used, if host name is not in original specifications then strip suffix node number from host name
- name: Set fact when performing SAP HANA Scale-Out
  ansible.builtin.set_fact:
    scaleout_origin_host_spec: "{{ inventory_hostname | regex_replace('^(.+?)\\d*$', '\\1') }}"
  when:
    - sap_vm_provision_calculate_sap_hana_scaleout_active_coordinator is defined
    - not inventory_hostname in lookup('ansible.builtin.vars', 'sap_vm_provision_' + sap_vm_provision_iac_platform + '_host_specifications_dictionary')[sap_vm_provision_host_specification_plan].keys()

- name: Provision IBM Cloud Virtual Server instance
  no_log: "{{ __sap_vm_provision_no_log }}"
  register: __sap_vm_provision_task_provision_host_single
  ibm.cloudcollection.ibm_is_instance:
    state: available
    name: "{{ inventory_hostname }}"
    image: "{{ (__sap_vm_provision_task_ibmcloud_os_image_list.resource.images | select('search', lookup('ansible.builtin.vars', 'sap_vm_provision_' + sap_vm_provision_iac_platform + '_host_os_image_dictionary')[sap_vm_provision_ibmcloud_vs_host_os_image]) | sort(reverse=True,case_sensitive=False,attribute='name') | first).id }}"
    profile: "{{ lookup('ansible.builtin.vars', 'sap_vm_provision_' + sap_vm_provision_iac_platform + '_host_specifications_dictionary')[sap_vm_provision_host_specification_plan][scaleout_origin_host_spec | default(inventory_hostname)].virtual_machine_profile }}"
    keys:
      - "{{ __sap_vm_provision_task_ibmcloud_ssh_public_key.resource.id }}"

    resource_group: "{{ __sap_vm_provision_task_ibmcloud_resource_group.resource.id }}"
    zone: "{{ sap_vm_provision_ibmcloud_availability_zone }}"
    vpc: "{{ __sap_vm_provision_task_ibmcloud_vpc_subnet.resource.vpc }}"

    # The Subnet assigned to the primary Virtual Network Interface (vNIC) cannot be changed
    # The Name and Security Group assigned to the Primary Network Interface (vNIC) are editable
    primary_network_interface:
      - name: "{{ inventory_hostname }}-vnic0"
        subnet: "{{ __sap_vm_provision_task_ibmcloud_vpc_subnet.resource.id }}"
        allow_ip_spoofing: "{{ lookup('ansible.builtin.vars', 'sap_vm_provision_' + sap_vm_provision_iac_platform + '_host_specifications_dictionary')[sap_vm_provision_host_specification_plan][scaleout_origin_host_spec | default(inventory_hostname)].disable_ip_anti_spoofing }}" # When disable the Anti IP Spoofing = true, then Allow IP Spoofing = true
        security_groups: "{{ __sap_vm_provision_task_ibmcloud_vpc_sg.results | map(attribute='resource.id') }}"
    #network_interfaces:

    auto_delete_volume: true
    boot_volume:
      - name: "{{ inventory_hostname }}-boot-0"

    metadata_service:
      - enabled: true
        protocol: https
        response_hop_limit: 5

    ibmcloud_api_key: "{{ sap_vm_provision_ibmcloud_api_key }}"


# Create flat list with names for each volume to be created.
- name: Set fact for target device map
  ansible.builtin.set_fact:
    storage_disks_map: |
      {% set disks_map = [] -%}
      {% for storage_item in lookup('ansible.builtin.vars', 'sap_vm_provision_' + sap_vm_provision_iac_platform + '_host_specifications_dictionary')[sap_vm_provision_host_specification_plan][scaleout_origin_host_spec | default(inventory_hostname)].storage_definition -%}
        {% for idx in range(0, storage_item.disk_count | default(1)) -%}
          {% if (storage_item.filesystem_type is defined) -%}
            {% if ('swap' in storage_item.filesystem_type and storage_item.swap_path is not defined)
            or ('swap' not in storage_item.filesystem_type and storage_item.nfs_path is not defined) -%}
              {% set vol = disks_map.extend([
              {
                'definition_key': storage_item.name,
                'name': storage_item.name + idx|string,
                'size': storage_item.disk_size | default(0),
                'type': storage_item.disk_type | default('general-purpose')
              }
              ]) %}
            {%- endif %}
          {%- endif %}
        {%- endfor %}
      {%- endfor %}
      {{ disks_map }}

- name: Provision IBM Cloud Block Storage volumes for IBM Cloud VS instance filesystems
  no_log: "{{ __sap_vm_provision_no_log }}"
  register: __sap_vm_provision_task_provision_host_single_volumes
  ibm.cloudcollection.ibm_is_volume:
    resource_group: "{{ __sap_vm_provision_task_ibmcloud_resource_group.resource.id }}"
    zone: "{{ sap_vm_provision_ibmcloud_availability_zone }}"
    name: "{{ inventory_hostname + '-vol-' + vol_item.name | replace('_', '-')}}"
    profile: "{{ vol_item.type }}"
    capacity: "{{ vol_item.size }}"
    ibmcloud_api_key: "{{ sap_vm_provision_ibmcloud_api_key }}"
  loop: "{{ storage_disks_map }}"
  loop_control:
    loop_var: vol_item
    index_var: vol_item_index
    label: "{{ vol_item.definition_key }}: {{ vol_item.name }} (size: {{ vol_item.size }})"
  when:
    - vol_item.size > 0

- name: Attach IBM Cloud Block Storage volumes as filesystem for IBM Cloud VS instance
  no_log: "{{ __sap_vm_provision_no_log }}"
  register: __sap_vm_provision_task_provision_host_single_volume_attachments
  ibm.cloudcollection.ibm_is_instance_volume_attachment:
    name: "{{ vol_item.resource.name }}-attach"
    volume: "{{ vol_item.resource.id }}"
    instance: "{{ __sap_vm_provision_task_provision_host_single.resource.id }}"
    delete_volume_on_attachment_delete: true
    delete_volume_on_instance_delete: true
    ibmcloud_api_key: "{{ sap_vm_provision_ibmcloud_api_key }}"
  loop: "{{ __sap_vm_provision_task_provision_host_single_volumes.results }}"
  loop_control:
    loop_var: vol_item
    index_var: vol_item_index
    label: "{{ vol_item.resource.name }}"


- name: Read IBM Cloud VS information
  no_log: "{{ __sap_vm_provision_no_log }}"
  register: __sap_vm_provision_task_provision_host_single_info
  ibm.cloudcollection.ibm_is_instance:
    name: "{{ __sap_vm_provision_task_provision_host_single.resource.name }}"
    ibmcloud_api_key: "{{ sap_vm_provision_ibmcloud_api_key }}"

- name: Add host facts
  ansible.builtin.set_fact:
    __sap_vm_provision_task_provision_host_single_volumes: "{{ __sap_vm_provision_task_provision_host_single_volumes }}"
    __sap_vm_provision_task_provision_host_single_info: "{{ __sap_vm_provision_task_provision_host_single_info }}"
  delegate_to: "{{ inventory_hostname }}"
  delegate_facts: true


- name: Create fact for delegate host IP
  ansible.builtin.set_fact:
    provisioned_private_ip: "{{ __sap_vm_provision_task_provision_host_single.resource.primary_network_interface[0].primary_ipv4_address }}"


- name: Copy facts to delegate host
  delegate_to: "{{ provisioned_private_ip }}"
  delegate_facts: true
  ansible.builtin.set_fact:
    delegate_sap_vm_provision_bastion_user: "{{ sap_vm_provision_bastion_user }}"
    delegate_sap_vm_provision_bastion_public_ip: "{{ sap_vm_provision_bastion_public_ip }}"
    delegate_sap_vm_provision_bastion_ssh_port: "{{ sap_vm_provision_bastion_ssh_port }}"
    delegate_sap_vm_provision_ssh_bastion_private_key_file_path: "{{ sap_vm_provision_ssh_bastion_private_key_file_path }}"
    delegate_sap_vm_provision_ssh_host_private_key_file_path: "{{ sap_vm_provision_ssh_host_private_key_file_path }}"
    delegate_private_ip: "{{ __sap_vm_provision_task_provision_host_single.resource.primary_network_interface[0].primary_ipv4_address }}"
    delegate_hostname: "{{ inventory_hostname }}"
    delegate_sap_vm_provision_dns_root_domain_name: "{{ sap_vm_provision_dns_root_domain }}"


### begin block, parameters will be applied to each task within the block
- name: Allow login from root OS User
  remote_user: root
  become: true
  become_user: root
  delegate_to: "{{ provisioned_private_ip }}"
  delegate_facts: true
  vars:
    ansible_ssh_private_key_file: "{{ delegate_sap_vm_provision_ssh_host_private_key_file_path }}"
    ansible_ssh_common_args: -o ConnectTimeout=180 -o ControlMaster=auto -o ControlPersist=3600s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardX11=no -o ProxyCommand='ssh -W %h:%p {{ delegate_sap_vm_provision_bastion_user }}@{{ delegate_sap_vm_provision_bastion_public_ip }} -p {{ delegate_sap_vm_provision_bastion_ssh_port }} -i {{ delegate_sap_vm_provision_ssh_bastion_private_key_file_path }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  block:

    - name: Create .ssh directory for root user
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        mode: '0744'

    - name: Create root authorized_keys file and entries
      ansible.builtin.copy:
        dest: /root/.ssh/authorized_keys
        mode: '0600'
        content: |
          {{ __sap_vm_provision_task_ibmcloud_ssh_public_key.resource.public_key }}

    - name: Permit root login
      register: __sap_vm_provision_task_os_sshd_config
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '(^PermitRootLogin no)'
        replace: 'PermitRootLogin yes'

    - name: Reload sshd service
      ansible.builtin.service:
        name: sshd
        state: reloaded
      when:
        - __sap_vm_provision_task_os_sshd_config.changed

### end of block


- name: Append loop value to register
  ansible.builtin.set_fact:
    __sap_vm_provision_task_provision_host_single: "{{ __sap_vm_provision_task_provision_host_single | combine( { 'host_node' : inventory_hostname } , { 'sap_host_type' : lookup('ansible.builtin.vars', 'sap_vm_provision_' + sap_vm_provision_iac_platform + '_host_specifications_dictionary')[sap_vm_provision_host_specification_plan][scaleout_origin_host_spec | default(inventory_hostname)].sap_host_type } , { 'sap_system_type' : (lookup('ansible.builtin.vars', 'sap_vm_provision_' + sap_vm_provision_iac_platform + '_host_specifications_dictionary')[sap_vm_provision_host_specification_plan][scaleout_origin_host_spec | default(inventory_hostname)].sap_system_type | default('')) } ) }}"

- name: Append output to merged register
  ansible.builtin.set_fact:
    register_provisioned_host_all: "{{ register_provisioned_host_all + [__sap_vm_provision_task_provision_host_single] }}"
