---
############################################
# Red Hat OpenShift Virtualization         #
############################################

# kubeconfig for Red Hat OpenShift cluster connection.
# If not provided, the kubeconfig will be read from the environment variables
# KUBECONFIG or K8S_AUTH_KUBECONFIG
# sap_vm_provision_kubevirt_vm_kubeconfig: /path/to/clusterconfigs/kubeconfig

# Namespace where the VM should be created in
sap_vm_provision_kubevirt_vm_target_namespace: sap

# Username to be created on guest
sap_vm_provision_kubevirt_vm_os_user: cloud-user

# Password for the above user
sap_vm_provision_kubevirt_vm_os_user_password: ""

# SSH key files, must be accessible on the ansible controller
sap_vm_provision_ssh_host_private_key_file_path: /path/to/id_rsa
sap_vm_provision_ssh_host_public_key_file_path: /path/to/id_rsa.pub

# RAM Overhead [GiB] for virt-launcher container, this can be small for VMs < 1 TB and without SRIOV but should be increased to 16 or more for VMs > 1TB
sap_vm_provision_kubevirt_vm_container_memory_overhead: 1

# hostname of the ansible controller
sap_vm_provision_execution_host: localhost # on AAP, this is localhost

# What's the host specification plan that should be rolled out?
sap_vm_provision_host_specification_plan: example_host_specification_plan

sap_vm_provision_kubevirt_vm_host_specifications_dictionary:
  example_host_specification_plan:
    host1: # Hostname, must be 13 characters or less
      # SMT-2 (i.e. 2 CPU Threads per CPU Core) is default for Intel CPU Hyper-Threading, optionally can be altered to SMT-1
      kubevirt_vm_cpu_smt: 2
      kubevirt_vm_cpu_cores: 2
      kubevirt_vm_memory_gib: 24
      sap_system_type: project_dev # project_dev, project_tst, project_prd
      sap_host_type: hana_primary # hana_primary, hana_secondary, anydb_primary, anydb_secondary, nwas_ascs, nwas_ers, nwas_pas, nwas_aas
      # Provide either an existing PVC or a URL for an OS image
      os_image: # either url or source_pvc_name have to be provided
        # URL for an image to be used
        #url: "docker://registry.redhat.io/rhel8/rhel-guest-image:8.8.0"
        #url: "docker://registry.redhat.io/rhel8/rhel-guest-image:8.10.0"
        #url: "docker://registry.redhat.io/rhel9/rhel-guest-image:9.4"
        url: "docker://registry.redhat.io/rhel9/rhel-guest-image:9.6"
        #url: "docker://registry.redhat.io/rhel10/rhel-guest-image:10.0"
        # Name for a PVC to be cloned
        # source_pvc_name: "rhel-8.8"
        namespace: openshift-virtualization-os-images
        size: "50Gi"
        access_modes:                    # e.g. ReadWriteMany | ReadWriteOnce
          - ReadWriteMany
      network_definition:
        - name: sapbridge
          type: bridge
          networkName: sapbridge-network-definition
          model: virtio
      storage_definition:
        - name: hana
          mountpoint: /hana
          disk_count: 1                  # default: 1
          disk_size: 2048                # size in GB, integer
          disk_type: sapstorage          # KubeVirt Storage Class
          access_modes:                  # e.g. ReadWriteMany | ReadWriteOnce
            - ReadWriteMany
      cloudinit:
        userData: |-
          #cloud-config
          timezone: Europe/Berlin
          hostname: host1
          user: {{ sap_vm_provision_kubevirt_vm_os_user if sap_vm_provision_kubevirt_vm_os_user is defined }}
          password: {{ sap_vm_provision_kubevirt_vm_os_user_password if sap_vm_provision_kubevirt_vm_os_user_password is defined }}
          chpasswd:
            expire: false
          ssh_authorized_keys:
            - "{{ lookup('ansible.builtin.file', sap_vm_provision_ssh_host_public_key_file_path ) if sap_vm_provision_ssh_host_public_key_file_path is defined }}"
        networkData: |-
          version: 2
          ethernets:
            eth0:
              dhcp4: true
