---

- name: Install netcat and lsof utils
  ansible.builtin.package:
    name:
      - nc
      - lsof
    state: present


# Must use while loop to avoid netcat process ending too early
# Required when using Load Balancers (i.e. Google Cloud, IBM Cloud, MS Azure)
# Temporary listener for SAP HANA or SAP AnyDB used is 55550
# Temporary listener for SAP NetWeaver ASCS used is 55551
# Temporary listener for SAP NetWeaver ERS used is 55552; must be different to ASCS Health Check Port to avoid ASCS VIP distributing to ERS host

- name: Start netcat temporary listen on port 55550 for SAP HANA or SAP AnyDB for 6 hours (until SAP installation complete) to respond to Load Balancer Health Check probe until Linux Pacemaker started
  ansible.builtin.shell: |
    if ! $(lsof -Pi :55550 -sTCP:LISTEN -t >/dev/null) ; then
    nohup timeout 6h bash -c "while true; do nc -vvv -l -k 55550 ; done" </dev/null >/dev/null 2>&1 &
    sleep 2
    fi
  when:
    - (groups["hana_secondary"] is defined and (groups["hana_secondary"]|length>0)) or (groups["anydb_secondary"] is defined and (groups["anydb_secondary"]|length>0))
    - (groups["hana_secondary"] is defined and inventory_hostname in groups["hana_primary"]) or (groups["anydb_secondary"] is defined and inventory_hostname in groups["anydb_primary"])
    - (ansible_product_name == 'Google Compute Engine') or (ansible_chassis_asset_tag == 'ibmcloud') or (ansible_chassis_vendor == 'Microsoft Corporation' and ansible_product_name == 'Virtual Machine')

- name: Start netcat temporary listen on port 55551 for SAP NetWeaver ASCS for 6 hours (until SAP installation complete) to respond to Load Balancer Health Check probe until Linux Pacemaker started
  ansible.builtin.shell: |
    if ! $(lsof -Pi :55551 -sTCP:LISTEN -t >/dev/null) ; then
    nohup timeout 6h bash -c "while true; do nc -vvv -l -k 55551 ; done" </dev/null >/dev/null 2>&1 &
    sleep 2
    fi
  when:
    - (groups["nwas_ers"] is defined and (groups["nwas_ers"]|length>0))
    - (groups["nwas_ers"] is defined and inventory_hostname in groups["nwas_ascs"])
    - (ansible_product_name == 'Google Compute Engine') or (ansible_chassis_asset_tag == 'ibmcloud') or (ansible_chassis_vendor == 'Microsoft Corporation' and ansible_product_name == 'Virtual Machine')

- name: Start netcat temporary listen on port 55552 for SAP NetWeaver ERS for 6 hours (until SAP installation complete) to respond to Load Balancer Health Check probe until Linux Pacemaker started
  ansible.builtin.shell: |
    if ! $(lsof -Pi :55552 -sTCP:LISTEN -t >/dev/null) ; then
    nohup timeout 6h bash -c "while true; do nc -vvv -l -k 55552 ; done" </dev/null >/dev/null 2>&1 &
    sleep 2
    fi
  when:
    - (groups["nwas_ers"] is defined and (groups["nwas_ers"]|length>0))
    - (groups["nwas_ers"] is defined and inventory_hostname in groups["nwas_ers"])
    - (ansible_product_name == 'Google Compute Engine') or (ansible_chassis_asset_tag == 'ibmcloud') or (ansible_chassis_vendor == 'Microsoft Corporation' and ansible_product_name == 'Virtual Machine')
