---

## Set Virtual IPs
# for AWS VPC, must be outside of VPC Subnet CIDR Range
# for MS Azure VNet, must be within the VNet Subnet CIDR Range attached to the Load Balancer
# for GCP VPC, must be within the VNet Subnet CIDR Range attached to the Load Balancer
# for IBM Cloud VPC, will automatically be within the VPC Subnet CIDR Range as Load Balancer owns/determines the Virtual IP; must not set VIP on the Host OS Network Interface as a secondary IP
# for IBM Power IaaS VLAN on IBM Cloud, must be within the VLAN Subnet CIDR Range
# for IBM PowerVM, must be within the VLAN Subnet CIDR Range


# Use of Primary IP Address default netmask prefix and/or the broadcast is automatic for Linux Pacemaker
# For AWS, this would be the VPC Subnet Netmask CIDR e.g. /24
# For MS Azure, this would be the VNet Subnet Netmask CIDR e.g. /24
# For GCP, this would be static Netmask CIDR /32 unless using custom OS Image - https://cloud.google.com/vpc/docs/create-use-multiple-interfaces#i_am_having_connectivity_issues_when_using_a_netmask_that_is_not_32

- name: Set fact for Broadcast Address and Prefix of the Primary IP
  ansible.builtin.set_fact:
    ip_broadcast_address: "{{ ansible_default_ipv4.broadcast | default('') }}"
    ip_cidr_prefix: "{{ ansible_default_ipv4.prefix | default('') }}"


#### HA of HANA Primary/Secondary ####

# Not required before SAP HANA installation or Linux Pacemaker installation, performed so the VIP connectivity can be tested
- name: Append temporary Virtual IP (VIP) to network interface for SAP HANA, will be replaced by Linux Pacemaker IPaddr2 Resource Agent
  ansible.builtin.shell: |
    if [ "{{ ip_broadcast_address }}" = "" ] && [ "{{ ip_cidr_prefix }}" = "" ]
    then
      ip address add {{ sap_vm_temp_vip_hana_primary | regex_replace('/.*', '') }}/32 brd + dev eth0
    elif [ "{{ ip_broadcast_address }}" != "" ]
    then
      ip address add {{ sap_vm_temp_vip_hana_primary | regex_replace('/.*', '') }} brd {{ ip_broadcast_address }} dev eth0
    elif [ "{{ ip_cidr_prefix }}" != "" ]
    then
      ip address add {{ sap_vm_temp_vip_hana_primary | regex_replace('/.*', '') }}/{{ ip_cidr_prefix }} brd + dev eth0
    fi
  when:
    - (groups["hana_secondary"] is defined and inventory_hostname in groups["hana_primary"]) and (groups["hana_secondary"] is defined and (groups["hana_secondary"]|length>0))
    - not ansible_chassis_asset_tag == 'ibmcloud'
  ignore_errors: true

# Not required before SAP HANA installation or Linux Pacemaker installation, performed so the VIP connectivity can be tested
- name: Append temporary Virtual IP (VIP) to network interface for SAP AnyDB, will be replaced by Linux Pacemaker IPaddr2 Resource Agent
  ansible.builtin.shell: |
    if [ "{{ ip_broadcast_address }}" = "" ] && [ "{{ ip_cidr_prefix }}" = "" ]
    then
      ip address add {{ sap_vm_temp_vip_anydb_primary | regex_replace('/.*', '') }}/32 brd + dev eth0
    elif [ "{{ ip_broadcast_address }}" != "" ]
    then
      ip address add {{ sap_vm_temp_vip_anydb_primary | regex_replace('/.*', '') }} brd {{ ip_broadcast_address }} dev eth0
    elif [ "{{ ip_cidr_prefix }}" != "" ]
    then
      ip address add {{ sap_vm_temp_vip_anydb_primary | regex_replace('/.*', '') }}/{{ ip_cidr_prefix }} brd + dev eth0
    fi
  when:
    - (groups["anydb_secondary"] is defined and inventory_hostname in groups["anydb_primary"]) and (groups["anydb_secondary"] is defined and (groups["anydb_secondary"]|length>0))
    - not ansible_chassis_asset_tag == 'ibmcloud'
  ignore_errors: true


#### HA of ASCS/ERS ####

# Required before running SAP SWPM
# Otherwise CSiManagerInterfaces.cpp will provide WARNING "The host with the name XXXXXX defined by SAPINST_USE_HOSTNAME is not a virtual host on the local host."
# And if the Virtual Hostname / Virtual IP cannot resolve, it will likely prevent SAP SWPM from completing the installation
- name: Append temporary Virtual IP (VIP) to network interface for SAP NetWeaver ASCS, will be replaced by Linux Pacemaker IPaddr2 Resource Agent
  ansible.builtin.shell: |
    if [ "{{ ip_broadcast_address }}" = "" ] && [ "{{ ip_cidr_prefix }}" = "" ]
    then
      ip address add {{ sap_vm_temp_vip_nwas_abap_ascs | regex_replace('/.*', '') }}/32 brd + dev eth0
    elif [ "{{ ip_broadcast_address }}" != "" ]
    then
      ip address add {{ sap_vm_temp_vip_nwas_abap_ascs | regex_replace('/.*', '') }} brd {{ ip_broadcast_address }} dev eth0
    elif [ "{{ ip_cidr_prefix }}" != "" ]
    then
      ip address add {{ sap_vm_temp_vip_nwas_abap_ascs | regex_replace('/.*', '') }}/{{ ip_cidr_prefix }} brd + dev eth0
    fi
  when:
    - (groups["nwas_ers"] is defined and inventory_hostname in groups["nwas_ascs"]) and (groups["nwas_ers"] is defined and (groups["nwas_ers"]|length>0))
    - not ansible_chassis_asset_tag == 'ibmcloud'
  ignore_errors: true

# Required before running SAP SWPM
# Otherwise CSiManagerInterfaces.cpp will provide WARNING "The host with the name XXXXXX defined by SAPINST_USE_HOSTNAME is not a virtual host on the local host."
# And if the Virtual Hostname / Virtual IP cannot resolve, it will likely prevent SAP SWPM from completing the installation
- name: Append temporary Virtual IP (VIP) to network interface for SAP NetWeaver ERS, will be replaced by Linux Pacemaker IPaddr2 Resource Agent
  ansible.builtin.shell: |
    if [ "{{ ip_broadcast_address }}" = "" ] && [ "{{ ip_cidr_prefix }}" = "" ]
    then
      ip address add {{ sap_vm_temp_vip_nwas_abap_ers | regex_replace('/.*', '') }}/32 brd + dev eth0
    elif [ "{{ ip_broadcast_address }}" != "" ]
    then
      ip address add {{ sap_vm_temp_vip_nwas_abap_ers | regex_replace('/.*', '') }} brd {{ ip_broadcast_address }} dev eth0
    elif [ "{{ ip_cidr_prefix }}" != "" ]
    then
      ip address add {{ sap_vm_temp_vip_nwas_abap_ers | regex_replace('/.*', '') }}/{{ ip_cidr_prefix }} brd + dev eth0
    fi
  when:
    - (groups["nwas_ers"] is defined and inventory_hostname in groups["nwas_ers"]) and (groups["nwas_ers"] is defined and (groups["nwas_ers"]|length>0))
    - not ansible_chassis_asset_tag == 'ibmcloud'
  ignore_errors: true


#### HA of PAS/AAS [rare, comment out] ####

# # Required before running SAP SWPM
# # Otherwise CSiManagerInterfaces.cpp will provide WARNING "The host with the name XXXXXX defined by SAPINST_USE_HOSTNAME is not a virtual host on the local host."
# # And if the Virtual Hostname / Virtual IP cannot resolve, it will likely prevent SAP SWPM from completing the installation
# - name: Append temporary Virtual IP (VIP) to network interface for SAP NetWeaver PAS, will be replaced by Linux Pacemaker IPaddr2 Resource Agent
#   ansible.builtin.shell: ip address add {{ sap_vm_temp_vip_nwas_abap_pas | regex_replace('/.*', '') }}/24 brd + dev eth0
#   when:
#     - (groups["nwas_pas"] is defined and inventory_hostname in groups["nwas_pas"]) and (groups["nwas_pas"] is defined and (groups["nwas_pas"]|length>0))
#     - not ansible_chassis_asset_tag == 'ibmcloud'
#   ignore_errors: true

# # Required before running SAP SWPM
# # Otherwise CSiManagerInterfaces.cpp will provide WARNING "The host with the name XXXXXX defined by SAPINST_USE_HOSTNAME is not a virtual host on the local host."
# # And if the Virtual Hostname / Virtual IP cannot resolve, it will likely prevent SAP SWPM from completing the installation
# - name: Append temporary Virtual IP (VIP) to network interface for SAP NetWeaver AAS, will be replaced by Linux Pacemaker IPaddr2 Resource Agent
#   ansible.builtin.shell: ip address add {{ sap_vm_temp_vip_nwas_abap_aas | regex_replace('/.*', '') }}/24 brd + dev eth0

#   when:
#     - (groups["nwas_pas"] is defined and inventory_hostname in groups["nwas_aas"]) and (groups["nwas_pas"] is defined and (groups["nwas_pas"]|length>0))
#     - not ansible_chassis_asset_tag == 'ibmcloud'
#   ignore_errors: true
