---
- name: Include node network
  ansible.builtin.include_tasks: node-network.yml
  with_items: "{{ __sap_hypervisor_node_preconfigure_register_worker.networks }}"
  loop_control:
    loop_var: __sap_hypervisor_node_preconfigure_register_worker_network
    index_var: __sap_hypervisor_node_preconfigure_register_worker_network_nr
  when: __sap_hypervisor_node_preconfigure_register_worker.networks is defined

- name: Wait for all k8s nodes to be ready
  kubernetes.core.k8s_info:
    kind: Node
    wait: true
    wait_condition:
      status: true
      type: Ready
    wait_sleep: 20
    wait_timeout: 600
