---
- name: Create the nmstate operator namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          kubernetes.io/metadata.name: openshift-nmstate
          name: openshift-nmstate
        name: openshift-nmstate
      spec:
        finalizers:
          - kubernetes

- name: Create the OperatorGroup
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        annotations:
          olm.providedAPIs: NMState.v1.nmstate.io
        generateName: openshift-nmstate-
        name: openshift-nmstate-tn6k8
        namespace: openshift-nmstate
      spec:
        targetNamespaces:
          - openshift-nmstate

- name: Pause to give operator a chance to install
  ansible.builtin.pause:
    minutes: 2

- name: Subscribe to the nmstate Operator
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        labels:
          operators.coreos.com/kubernetes-nmstate-operator.openshift-nmstate: ""
        name: kubernetes-nmstate-operator
        namespace: openshift-nmstate
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: kubernetes-nmstate-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Pause to give operator a chance to install
  ansible.builtin.pause:
    minutes: 5

- name: Create instance of the nmstate operator
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: nmstate.io/v1
      kind: NMState
      metadata:
        name: nmstate

- name: Pause to give instance a chance to come up
  ansible.builtin.pause:
    minutes: 5
