---
- name: Label worker with invtsc flag
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: default
        labels:
          'feature.node.kubernetes.io/cpu-feature-invtsc': enabled
