---
# tasks file for sap_hypervisor_node_preconfigure

- name: Stop and disable kernel same page merging (KSM)
  ansible.builtin.systemd:
    name: ksm
    state: stopped
    enabled: false

- name: Stop and disable kernel same page merging (KSM) tuning daemon
  ansible.builtin.systemd:
    name: ksmtuned
    state: stopped
    enabled: false

- name: Check CPU Stepping
  ansible.builtin.shell: set -o pipefail && lscpu | awk '/Stepping/{print $2}'
  register: cpu_stepping_output
  changed_when: cpu_stepping_output.rc != 0

- name: Register CPU stepping as fact
  ansible.builtin.set_fact:
    cpu_stepping: "{{ cpu_stepping_output.stdout }}"
  become: true
  become_user: root

# skylake:
- name: Set ple_gap=0 on Intel Skylake CPU Platform
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/kvm.conf
    line: options kvm_intel ple_gap=0
  when: cpu_stepping == "4"
  become: true
  become_user: root

# skylake
- name: Set spectre_v2=retpoline on Intel Skylake CPU Platform
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    backrefs: true
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ item }}).*). *$'
    line: "\\1 {{ item }}\""
  with_items:
    - "spectre_v2=retpoline"
  notify: __sap_hypervisor_node_preconfigure_regenerate_grub2_conf_handler
  tags: grubconfig
  when: cpu_stepping == "4"
  become: true
  become_user: root

- name: "Set kvm.nx_huge_pages to {{ sap_hypervisor_node_preconfigure_kvm_nx_huge_pages }}"
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    backrefs: true
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ item }}).*). *$'
    line: "\\1 {{ item }}\""
  with_items:
    - "kvm.nx_huge_pages={{ sap_hypervisor_node_preconfigure_kvm_nx_huge_pages }}"
  notify: __sap_hypervisor_node_preconfigure_regenerate_grub2_conf_handler
  tags: grubconfig
  when: sap_hypervisor_node_preconfigure_kvm_nx_huge_pages is defined
  become: true
  become_user: root

- name: Set seccomp_sanbox=0
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    backup: true
    backrefs: true
    state: present
    regexp: 'seccomp_sandbox'
    line: "seccomp_sandbox = 0"
  become: true
  become_user: root

- name: Include allocate hughepages at runtime
  ansible.builtin.include_tasks: allocate-hugepages-at-runtime.yml
  when: sap_hypervisor_node_preconfigure_reserve_hugepages == "runtime"

- name: Reserve Hugepages statically
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    backrefs: true
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ item }}).*). *$'
    line: "\\1 {{ item }}\""
  with_items:
    - default_hugepagesz=1GB
    - hugepagesz=1GB
    - hugepages={{ (ansible_memtotal_mb / 1024) | int - sap_hypervisor_node_preconfigure_reserved_ram }}
  notify: __sap_hypervisor_node_preconfigure_regenerate_grub2_conf_handler
  tags: grubconfig
  when: sap_hypervisor_node_preconfigure_reserve_hugepages == "static"
  become: true
  become_user: root

- name: Enable IOMMU PT
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    backrefs: true
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ item }}).*). *$'
    line: "\\1 {{ item }}\""
  with_items:
    - intel_iommu=on
    - iommu=pt
  notify: __sap_hypervisor_node_preconfigure_regenerate_grub2_conf_handler
  tags: grubconfig
  become: true
  become_user: root

# See SAP Note 2737837 - SAP HANA and the Intel Transactional Synchronization Extensions Capability
- name: Enable TSX
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    backrefs: true
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ item }}).*). *$'
    line: "\\1 {{ item }}\""
  with_items:
    - "tsx={{ sap_hypervisor_node_preconfigure_tsx }}"
  notify: __sap_hypervisor_node_preconfigure_regenerate_grub2_conf_handler
  tags: grubconfig
  become: true
  become_user: root
