---
- name: Display sap_hypervisor_node_preconfigure_assert
  ansible.builtin.debug:
    var: sap_hypervisor_node_preconfigure_assert

- name: Set filename prefix to empty string if role is run in normal mode
  ansible.builtin.set_fact:
    assert_prefix: ""

- name: Prepend filename with assert string if role is run in assert mode
  ansible.builtin.set_fact:
    assert_prefix: "assert-"
  when: sap_hypervisor_node_preconfigure_assert

- name: Include "{{ assert_prefix }}installation.yml"
  ansible.builtin.include_tasks: '{{ assert_prefix }}installation.yml'

- name: Include "{{ assert_prefix }}configuration.yml"
  ansible.builtin.include_tasks: '{{ assert_prefix }}configuration.yml'

- name: Include "{{ assert_prefix }}set-tuned-profile.yml"
  ansible.builtin.include_tasks: '{{ assert_prefix }}set-tuned-profile.yml'

- name: Include "{{ assert_prefix }}rhv-hooks.yml"
  ansible.builtin.include_tasks: "{{ assert_prefix }}rhv-hooks.yml"
  loop:
    - 50_hana
    - 50_iothread_pinning
