---
- name: Preparation Ansible Play for SAP VM provisioning on Red Hat OpenShift Virtualization
  hosts: all
  gather_facts: false
  serial: 1
  vars:
    sap_vm_provision_iac_type: ansible
    sap_vm_provision_iac_platform: kubevirt_vm
  pre_tasks:
    # Alternative to executing ansible-playbook with -e for Ansible Extravars file
    # - name: Include sample variables for Red Hat Openshift Virtualization
    #   ansible.builtin.include_vars: ./vars/sample-variables-sap-vm-provision-redhat-ocpv.yml
  tasks:

    - name: Save inventory_host as execution_host
      ansible.builtin.set_fact:
        sap_vm_provision_execution_host: "{{ inventory_hostname }}"
      when: sap_vm_provision_execution_host is not defined

    - name: Save ansible_user as execution_host user
      ansible.builtin.set_fact:
        __sap_vm_provision_kubevirt_vm_register_execution_host_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

    - name: Create Tempdir
      ansible.builtin.tempfile:
        state: directory
        suffix: "_sap_vm_provision_kubevirt_vm"
      register: __sap_vm_provision_kubevirt_vm_register_tmpdir

    - name: Use kubeconfig file specified in environment variable K8S_AUTH_KUBECONFIG | KUBECONFIG if sap_vm_provision_kubevirt_vm_kubeconfig_path is not defined
      when: >
        sap_vm_provision_kubevirt_vm_kubeconfig is not defined or
        sap_vm_provision_kubevirt_vm_kubeconfig == None or
        sap_vm_provision_kubevirt_vm_kubeconfig == ''
      ansible.builtin.set_fact:
        sap_vm_provision_kubevirt_vm_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') | default(lookup('env', 'KUBECONFIG'), true) }}"

    - name: Ensure that kubeconfig is set
      ansible.builtin.assert:
        that:
          - sap_vm_provision_kubevirt_vm_kubeconfig is defined
          - sap_vm_provision_kubevirt_vm_kubeconfig is not none
          - sap_vm_provision_kubevirt_vm_kubeconfig | length > 0
        fail_msg: "sap_vm_provision_kubevirt_vm_kubeconfig is required."

    - name: Create dynamic inventory group for Ansible Role sap_vm_provision and provide configuration such as execution_host, kubeconfig, etc.
      ansible.builtin.add_host:
        name: "{{ item }}"
        group: sap_vm_provision_target_inventory_group
        sap_vm_provision_iac_type: ansible
        sap_vm_provision_iac_platform: kubevirt_vm
        sap_vm_provision_execution_host: "{{ sap_vm_provision_execution_host }}"
        __sap_vm_provision_kubevirt_vm_register_execution_host_user: "{{ __sap_vm_provision_kubevirt_vm_register_execution_host_user }}"
        __sap_vm_provision_kubevirt_vm_register_tmpdir: "{{ __sap_vm_provision_kubevirt_vm_register_tmpdir }}"
        sap_vm_provision_kubevirt_vm_kubeconfig: "{{ sap_vm_provision_kubevirt_vm_kubeconfig }}"
      loop: "{{ sap_vm_provision_kubevirt_vm_host_specifications_dictionary[sap_vm_provision_host_specification_plan].keys() }}"

- name: Ansible Play to provision VMs for SAP
  hosts: sap_vm_provision_target_inventory_group # Ansible Play target hosts pattern, use Inventory Group created by previous Ansible Task (add_host)
  gather_facts: false
  environment:
    K8S_AUTH_KUBECONFIG: "{{ sap_vm_provision_kubevirt_vm_kubeconfig }}"
    KUBECONFIG: "{{ sap_vm_provision_kubevirt_vm_kubeconfig }}"
  tasks:

    - name: Execute Ansible Role sap_vm_provision
      when: sap_vm_provision_iac_type == "ansible" or sap_vm_provision_iac_type == "ansible_to_terraform"
      block:
        - name: Include sap_vm_provision Ansible Role
          ansible.builtin.include_role:
            name: community.sap_infrastructure.sap_vm_provision

      always:
        - name: Remove temporary directory on execution_host
          delegate_to: "{{ sap_vm_provision_execution_host }}"
          ansible.builtin.file:
            state: absent
            path: "{{ __sap_vm_provision_kubevirt_vm_register_tmpdir.path }}"
