---
galaxy_info:
  namespace: community
  role_name: sap_hypervisor_node_preconfigure
  author: Nils Koenig
  description: Provide the configuration of hypervisors for SAP workloads
  license: Apache-2.0
  min_ansible_version: "2.9"
  galaxy_tags: ['sap', 'hana', 'rhel', 'redhat', 'openshift']
  platforms:
    - name: RHEL
      versions:
        8
dependencies: []
