---

# Workflow for ansible-lint of a role

name: ansible-lint of the role sap_vm_temp_vip

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_vm_temp_vip/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_vm_temp_vip/**'

  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install test dependencies
        run: |
          pip3 install \
            ansible-core~=2.18.0 \
            ansible~=11.0.0 \
            ansible-lint~=25.1.0 \
            ansible-compat~=25.1.0

      - name: Run ansible-lint
        working-directory: /home/runner/work/community.sap_infrastructure/community.sap_infrastructure/roles/sap_vm_temp_vip
        run: ansible-lint
