---

# Workflow for ansible-lint of a role

name: ansible-lint of the role sap_vm_verify

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_vm_verify/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_vm_verify/**'

  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          pip3 install ansible==9.1.0
          pip3 install ansible-compat==4.1.10
          pip3 install ansible-core==2.16.2
          pip3 install ansible-lint==6.22.1
          pip3 install jmespath==1.0.1

      - name: Run ansible-lint
        working-directory: /home/runner/work/community.sap_infrastructure/community.sap_infrastructure/roles/sap_vm_verify
        run: ansible-lint
