---

# Workflow for ansible-lint of the collection

name: ansible-lint of the collection

on:
  schedule:
    - cron: '31 13 * * 1'

  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install test dependencies
        run: |
          pip3 install \
            ansible-core~=2.18.0 \
            ansible~=11.0.0 \
            ansible-lint~=25.1.0 \
            ansible-compat~=25.1.0 \
            jmespath~=1.0.0

      - name: Install dependencies for Ansible
        run: ansible-galaxy collection install -r /home/runner/work/community.sap_infrastructure/community.sap_infrastructure/requirements.yml

      - name: Move the collection to the correct location - Create new directory
        run: mkdir -p /home/runner/.ansible/collections/ansible_collections/community

      - name: Move the collection to the correct location - Move the collection
        working-directory: /home/runner/
        run: mv /home/runner/work/community.sap_infrastructure/community.sap_infrastructure /home/runner/.ansible/collections/ansible_collections/community

      - name: Move the collection to the correct location - Rename the directory
        working-directory: /home/runner/
        run: mv /home/runner/.ansible/collections/ansible_collections/community/community.sap_infrastructure /home/runner/.ansible/collections/ansible_collections/community/sap_infrastructure

      - name: Run ansible-lint
        working-directory: /home/runner/.ansible/collections/ansible_collections/community/sap_infrastructure
        run: ansible-lint

      - name: Move the collection to its previous location
        working-directory: /home/runner/
        run: mv /home/runner/.ansible/collections/ansible_collections/community/sap_infrastructure /home/runner/work/community.sap_infrastructure/community.sap_infrastructure
