---
name: Ansible Lint - sap_vm_temp_vip

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_vm_temp_vip/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_vm_temp_vip/**'

  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

        # Use @v25 to automatically track the latest release from the year 2025.
        # ansible-lint uses Calendar Versioning (e.g., v25.9.0 -> YYYY.MM.PATCH).
        # Avoid using @main, which can introduce breaking changes unexpectedly.
      - uses: ansible/ansible-lint@v25
        with:
          # Sets the linter's execution path to the specific role's directory.
          # Uses role specific .ansible-lint, if present.
          working_directory: ./roles/sap_vm_temp_vip
          # Use the shared requirements file from the collection root for dependency context.
          requirements_file: ../../requirements.yml
